Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-047a51fa27710816e # Amazon Linux AMI in N.Virginia
      Tags:
        - Key: Name
          Value: DanielExample